version: "3"
services:
  node_app:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - 3000:3000
  nginx_app:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 3001:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html