version: '3'
services:
  api:
    image: shanyue/whoami
    ports:
      - 8000:3000
  cache:
    image: nginx:alpine
    ports:
      - 8001:80
    volumes:
      - ./cache.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  50x:
    image: nginx:alpine
    ports:
      - 8002:80
    volumes:
      - ./50x.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  compress_gzip:
    image: nginx:alpine
    ports:
      - 8003:80
    volumes:
      - ./compress_gzip.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  # 如何为 nginx 中添加 module https://github.com/nginxinc/docker-nginx/tree/master/modules
  compress_brotli:
    build:
      context: ./brotli/
      args:
        ENABLED_MODULES: brotli
    ports:
      - 8004:80
    volumes:
      - ./compress_brotli.conf:/etc/nginx/conf.d/default.conf
      - ./compress_brotli_nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/share/nginx/html