version: '3'
services:
  api:
    image: shanyue/whoami
    ports:
      - 8000:3000
  cache:
    image: nginx:alpine
    ports:
      - 8001:80
    volumes:
      - ./cache.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  50x:
    image: nginx:alpine
    ports:
      - 8002:80
    volumes:
      - ./50x.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html