version: '3.0.0'
services:
  # 配置 index.html 强缓存 60s 时间
  cache:
    image: nginx:alpine
    ports:
      - 8001:80
    volumes:
      - ./cache.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html