version: "3"
services:
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.tangzhenming.com`)"
      # 基本认证（基础授权验证）访问配置
      - "traefik.http.middlewares.test-auth.basicauth.users=tang:$$apr1$$EJReCMcY$$BZrJQ8Lokz9gxYAKlQzhN."
      - "traefik.http.routers.whoami.middlewares=test-auth@docker"
      # HTTPS
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
networks:
  default:
    external:
      name: traefik_default
