version: '3.3'
services:
  cra:
    build: 
      context: .
      dockerfile: cra.Dockerfile
    ports:
      - "8000:3000"
  cra_refactor_time:
    build: 
      context: .
      dockerfile: cra_refactor_time.Dockerfile
    ports:
      - "8001:3000"
  cra_refactor_size:
    build: 
      context: .
      dockerfile: cra_refactor_size.Dockerfile
    ports:
      - "8002:80"
  cra_refactor:
    build:
      dockerfile: cra_refactor.Dockerfile
    ports:
      - "8003:80"